export const autoUsers = [
  'Tony Gwynn',
  'LeBron',
  'Seau',
  'LaDanian Tomlinson',
  'bsturd',
  'Sleeper',
  'Scotty Pippen',
  'Kawhi Leonard',
  'Travis Kelce',
  'Donna Kelce',
  'Taylor Swift',
  'Gwen Stephani',
  'Thom Yorke',
  'Carly Rae Jepsen',
  'Fernando Tatis Jr.',
  'Manny Machado',
  'Annie Clark',
  'April Music Works',
]
